

# Production
baseURL = "https://cumulocity.com/guides/10.14.0"

languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Cumulocity IoT Guides"
theme = "c8ydocs"
paginate = 12
# canonifyurls = false
# publishDir = "public/site"
# googleAnalytics = "UA-xxxxxxxx-x"
summaryLength = 30
buildFuture = true

relativeURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      style = "solarized-dark256"

[author]
  name = "Carlos Ceia @ Cumulocity"



[params]
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  # dateFormat = "2 January 2006"

  # Global keywords configuration. Following keywords will be add to every pages
  keywords = ["Software AG Cloud", "Cumulocity IoT", "Internet of things", "analytics", "devices", "connect"]

  description = "Resources for connecting your machines and devices to the Internet of Things"
  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true

  logo = "images/cumulocity-iot.svg"

  guidesRedirect = "https://www.softwareag.cloud/site/dev-center/cumulocity-iot.html"

  # Your favicon path, default is "/favicon.png"
  favicon = "https://cumulocity.com/favicon.ico"

  # Content variables for Frontmatter titles
  product_c8y_iot = "Cumulocity IoT"
  company_sag = "Software AG"
  enterprise_tenant = "Enterprise tenant"

# Customize
  [params.footer]
    copyright = "Cumulocity GmbH | All rights reserved"
    c8ylink = "https://www.softwareag.cloud/site/product/cumulocity-iot.html"
